package dev.sweetberry.wwizardry.mixin;

import com.terraformersmc.terraform.boat.api.TerraformBoatType;
import com.terraformersmc.terraform.boat.api.TerraformBoatTypeRegistry;
import com.terraformersmc.terraform.boat.impl.TerraformBoatTrackedData;
import net.minecraft.entity.data.TrackedDataHandler;
import org.quiltmc.qsl.entity.networking.api.tracked_data.QuiltTrackedDataHandlerRegistry;
import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import java.util.Optional;

@Mixin(value = TerraformBoatTrackedData.class, remap = false)
public final class Mixin_TerraformBoatTrackedData {
	@Shadow
	@Final
	public static TrackedDataHandler<Optional<TerraformBoatType>> HANDLER;

	private Mixin_TerraformBoatTrackedData() {
		throw new AssertionError("No instance for you!"); // generated by CoPilot
	}

	@Inject(method = "register", at = @At("HEAD"), cancellable = true)
	private static void register(CallbackInfo ci) {
		ci.cancel();
		QuiltTrackedDataHandlerRegistry.register(TerraformBoatTypeRegistry.INSTANCE.getKey().getRegistry(), HANDLER);
	}
}
