steps:
  - name: build
    image: "eclipse-temurin:17.0.10_7-jdk-alpine"
    commands:
      - ./gradlew build
  - name: notify
    image: appleboy/drone-discord
    settings:
      webhook_id: $WEBHOOK_ID
      webhook_token: $WEBHOOK_TOKEN
    secrets: [ webhook_id, webhook_token ]
