steps:
  - name: build
    image: "eclipse-temurin:17.0.10_7-jdk-alpine"
    commands:
      - ./gradlew build
  - name: notify
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: webhook_id
      webhook_token:
        from_secret: webhook_token
