[versions]
minecraft = "1.21.1"
fabric_loader = "0.15.11"
neoforge = "21.1.57"

mixin = "0.8.5"
mixin_extras = "0.3.5"

fabric_api = "0.104.0+1.21.1"

terrablender = "1.21-4.0.0.1"

emi = "1.1.12+1.21"
modmenu = "11.0.1"

trimmed_fabric = "1.21-3.0.0+fabric"
trimmed_neoforge = "1.21-3.0.0+neoforge"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
mixin_extras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixin_extras" }

# Common
terrablender_common = { module = "com.github.glitchfiend:TerraBlender-common", version.ref = "terrablender" }
terrablender_fabric = { module = "com.github.glitchfiend:TerraBlender-fabric", version.ref = "terrablender" }
terrablender_neoforge = { module = "com.github.glitchfiend:TerraBlender-neoforge", version.ref = "terrablender" }

emi_common = { module = "dev.emi:emi-xplat-mojmap", version.ref = "emi" }
emi_fabric = { module = "dev.emi:emi-fabric", version.ref = "emi" }
emi_neoforge = { module = "dev.emi:emi-neoforge", version.ref = "emi" }

trimmed_neoforge = { module = "maven.modrinth:trimmed", version.ref = "trimmed_neoforge" }
trimmed_fabric = { module = "maven.modrinth:trimmed", version.ref = "trimmed_fabric" }

# Neoforge
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

# Fabric
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
mixin = ["mixin", "mixin_extras"]

include_common = ["terrablender_common"]

include_fabric = ["terrablender_fabric", "trimmed_fabric"]

include_neoforge = ["terrablender_neoforge", "trimmed_neoforge"]

compat_fabric = ["emi_fabric", "modmenu"]

[plugins]
idea_ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.1.8" }
loom = { id = "fabric-loom", version = "1.7-SNAPSHOT" }
vanilla_gradle = { id = "org.spongepowered.gradle.vanilla", version = "0.2.1-SNAPSHOT" }
neogradle = { id = "net.neoforged.gradle.userdev", version = "7.0.107" }
mod_dev_gradle = { id = "net.neoforged.moddev", version = "2.0.16-beta" }
