plugins {
	id 'java'
	alias libs.plugins.mod.dev.gradle
    id 'java-library'
}

archivesBaseName = project.archives_base_name
version = rootProject.version + "-neoforge"

neoForge {
	version = libs.versions.neoforge.get()
	var at = file('src/main/resources/accesstransformer.cfg')
	if (at.exists()) {
		accessTransformers = [at.absolutePath]
	}
	runs {
		configureEach {
			systemProperty('neoforge.enabledGameTestNamespaces', "wwizardry")
			ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
		}
		client {
			client()
		}
		data {
			data()
		}
		server {
			server()
		}
	}
	mods {
		"wwizardry" {
			sourceSet sourceSets.main
		}
	}
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
	maven {
		name = "TerraformersMC"
		url = "https://maven.terraformersmc.com/"
	}
	maven {
		name = "Forge"
		url = "https://maven.minecraftforge.net/"
	}
}

//sourceSets.main.resources { srcDir 'src/generated/resources' }

def classify(module, classifier) {
	var m = module.get()
	return "${m.module.group}:${m.module.name}:${m.version}:$classifier"
}

dependencies {
	implementation libs.neoforge
	compileOnly project(":common")

	compileOnly classify(libs.emi.neoforge, "api")
	testCompileOnly classify(libs.emi.neoforge, "api")
	runtimeOnly libs.emi.neoforge

	implementation libs.bundles.include.neoforge
	testImplementation libs.bundles.include.neoforge
//	jarJar libs.bundles.include.neoforge
}

Spec<Task> notNeoTask = { Task it -> !it.name.startsWith("neo") } as Spec<Task>

tasks.withType(JavaCompile).matching(notNeoTask).configureEach {
	source(project(":common").sourceSets.main.allSource)
	it.options.encoding = 'UTF-8'
	it.options.release = 21
	dependsOn ":generateData"
	dependsOn processResources
}

tasks.withType(Javadoc).matching(notNeoTask).configureEach {
	source(project(":common").sourceSets.main.allJava)
}

processResources {
	from project(":common").sourceSets.main.resources
	inputs.property 'version', version

	filesMatching('META-INF/neoforge.mods.toml') {
		expand "version": version
	}
}

test.onlyIf { false }
compileTestJava.onlyIf { false }
